import type { Metadata } from "next";
import { Geist_Mono, Cinzel } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";

const cinzel = Cinzel({
  variable: "--font-deco",
  subsets: ["latin"],
  weight: ["400"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.className} ${geistMono.variable} antialiased`}
      >
        
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}